### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by avanisho** [thasti/fft#2] opened 2020-06-15 06:12 UTC
Hi,
I tried to run the test bench by typing make in fft/vrf folder. I got following error.

(base) D:\Work\Vivado\Booster_BbyB\fft-thasti\fft\vrf>make
make results.xml
make[1]: Entering directory '/d/Work/Vivado/Booster_BbyB/fft-thasti/fft/vrf'
make[1]: *** No rule to make target '/../../counter/rtl/counter.vhd', needed by
'analyse'.  Stop.
make[1]: Leaving directory '/d/Work/Vivado/Booster_BbyB/fft-thasti/fft/vrf'
C:\\Users\\DELL\\Anaconda3\\Lib\\site-packages\\cocotb\\share/makefiles/Makefile
.sim:79: recipe for target 'sim' failed
make: *** [sim] Error 2

Kindly suggest a solution for this.

Thank you.

**Comment by thasti** [comment] 2020-06-15 06:24
Just tried that in a clean venv, installing cocotb 1.3.1, numpy and matplotlib and cannot reproduce your issue. I'm not running Windows, so can't provide any support here. The error message does not indicate something obvious to me.

**Comment by thasti** [comment] 2020-06-17 14:05
Closing this for the time being, let me know in case you have a follow-up or fix for this.

**Closed as completed by thasti** 2020-06-17 14:05 UTC
